output_dir: /usr/share/nginx/html
static_dir: /build/static
template_dir: /build/templates
post_dir: posts
articles:
  config: /build/articles/config
  posts: /build/articles/posts
additional_pages:
  index: 
    url: index.html
  sitemap: 
    url: sitemap.xml
  feed:
    url: index.xml
    add_path: feed/
  archive:
    url: archive.html
    title: Archives
  notfound:
    url: 404.html
    title: Page Not Found
  forbidden:
    url: 403.html
    title: Access Forbidden
templates:
  archive: archive.html
  article: blog.html
  index: index.html
  feed: feed.xml
  sitemap: sitemap.xml
  notfound: 404.html
  forbidden: 403.html
site_name: Benjamin Cane
site_description: A blog about Linux Systems Administration, Automation, Python and other DevOps-y topics
site_shortdesc: A Systems Architect writing about Linux Systems Administration
site_thumbnail: http://bencane.com/img/thumbnails/shell.png
site_url: http://bencane.com
site_feed: http://feed.bencane.com
site_keywords: 
  - linux
  - unix
  - sysadmin
  - sysadmin blog
  - devops
  - DevOps How to
  - DevOps Blog
  - Linux Blog
  - linux blog
  - sysadmin best practices
  - systems administration
  - ubuntu
  - redhat
  - linux os
  - Linux Server
  - bash shell
  - linux for dummies
  - learning linux
  - linux operating system
  - Linux tutorials
  - Linux how to
  - Sysadmin tutorials
  - Sysadmin How To
site_author: Benjamin Cane
site_authorlink: https://plus.google.com/+BenjaminCane
