author: bencane
comments: true
date: 2011-10-06 19:32:39+00:00
popularity: None
slug: bind-checking-a-zone-record-for-errors
title: 'bind: Checking a zone record for errors'
post_id: 53
categories:
- All Articles
- Applications
- Bind
- DNS
- How To &amp; Tutorials
tags:
- bind
- dns
- linkedin
- linux
- tech
- unix
file: 2011-10-06-bind-checking-a-zone-record-for-errors.md
published: True
pubdate: Thu, 06 Oct 2011 00:00:00 +0000
