author: bencane
comments: true
date: 2011-08-21 13:33:06+00:00
popularity: None
slug: websphere-mq-saveqmgr
title: 'Websphere MQ: saveqmgr'
post_id: 40
categories:
- How To &amp; Tutorials
tags:
- ibm
- linux
- mq
- tech
- unix
file: 2011-08-21-websphere-mq-saveqmgr.md
published: True
pubdate: Sun, 21 Aug 2011 00:00:00 +0000
