author: bencane
comments: true
date: 2011-07-08 02:08:00+00:00
popularity: None
slug: usermod-appending-to-additional-groups
title: 'usermod: Appending to Additional Groups'
post_id: 9
categories:
- Administration
- How To &amp; Tutorials
- Linux
- Linux Commands
tags:
- linux
- tech
- usermod
file: 2011-07-08-usermod-appending-to-additional-groups.md
published: True
pubdate: Fri, 08 Jul 2011 00:00:00 +0000
