author: bencane
comments: true
date: 2011-08-01 03:50:00+00:00
popularity: None
slug: smf-enable-apache-solaris
title: 'SMF: Enable apache [Solaris]'
post_id: 21
categories:
- Command Line
- How To &amp; Tutorials
- Solaris
- Unix
- Unix Distributions
tags:
- oracle
- solaris
- tech
file: 2011-08-01-smf-enable-apache-solaris.md
published: True
pubdate: Mon, 01 Aug 2011 00:00:00 +0000
