author: bencane
comments: true
date: 2011-08-24 07:39:47+00:00
popularity: None
slug: debian-packages-installing
title: 'Debian Packages: Installing'
post_id: 42
categories:
- How To &amp; Tutorials
- Linux
- Linux Commands
- Linux Distributions
- Ubuntu
tags:
- debian
- linux
- tech
file: 2011-08-24-debian-packages-installing.md
published: True
pubdate: Wed, 24 Aug 2011 00:00:00 +0000
