author: bencane
comments: true
date: 2011-08-28 20:31:05+00:00
popularity: None
slug: top-show-cpu-usage-on-all-cores
title: 'Top: Show CPU Usage on all cores'
post_id: 45
categories:
- Command Line
- How To &amp; Tutorials
- Linux
- Linux Commands
tags:
- linux
- tech
- unix
file: 2011-08-28-top-show-cpu-usage-on-all-cores.md
published: True
pubdate: Sun, 28 Aug 2011 00:00:00 +0000
