author: bencane
comments: true
date: 2011-08-03 03:44:00+00:00
popularity: None
slug: yum-search-and-install
title: 'Yum: Search and Install'
thumbnail: http://bencane.com/img/thumbnails/yum.png
post_id: 23
categories:
- Command Line
- How To &amp; Tutorials
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- fedora
- linux
- tech
- yum
file: 2011-08-03-yum-search-and-install.md
published: True
pubdate: Wed, 03 Aug 2011 00:00:00 +0000
