author: bencane
comments: true
date: 2011-10-14 20:30:06+00:00
popularity: None
slug: gzip-restoring-original-filename
title: 'gzip: Restoring original filename'
post_id: 55
categories:
- All Articles
- Command Line
- How To &amp; Tutorials
- Linux
- Linux Commands
- Troubleshooting
- Unix
- Unix Commands
tags:
- gzip
- linkedin
- linux
- tech
- unix
file: 2011-10-14-gzip-restoring-original-filename.md
published: True
pubdate: Fri, 14 Oct 2011 00:00:00 +0000
