author: bencane
comments: true
date: 2011-12-12 23:08:38+00:00
popularity: None
slug: creating-a-read-only-backup-user-for-mysqldump
title: Creating a read-only backup user for mysqldump
thumbnail: http://bencane.com/img/thumbnails/mysql.jpg
description: How to create a read-only user that can be used for MySQL backups with mysqldump
post_id: 59
categories:
- Administration
- All Articles
- Applications
- Databases
- How To &amp; Tutorials
- MySQL
- Security
tags:
- linkedin
- linux
- mysql
- tech
- unix
file: 2011-12-12-creating-a-read-only-backup-user-for-mysqldump.md
published: True
pubdate: Mon, 12 Dec 2011 00:00:00 +0000
