author: bencane
comments: true
date: 2011-07-01 23:11:38+00:00
popularity: None
slug: bash-random
title: Bash $RANDOM
post_id: 5
categories:
- How To &amp; Tutorials
- Linux Commands
- Shell Scripting
- Unix Commands
tags:
- bash
- linux
- unix
file: 2011-07-01-bash-random.md
published: True
pubdate: Fri, 01 Jul 2011 00:00:00 +0000
