date: 2011-06-25 01:24:57+00:00
slug: sfdisk-goodies
title: sfdisk Goodies
post_id: 3
categories:
- Command Line
- How To &amp; Tutorials
- Linux
- Linux Commands
tags:
- linux
- tech
- unix
popularity: None
file: 2011-06-25-sfdisk-goodies.md
published: True
pubdate: Sat, 25 Jun 2011 00:00:00 +0000
