author: bencane
comments: true
date: 2011-09-06 20:02:06+00:00
popularity: None
slug: fsck-force-a-filesystem-check-on-next-reboot
title: 'fsck: Force a filesystem check on next reboot'
post_id: 47
categories:
- Administration
- All Articles
- How To &amp; Tutorials
- Linux
tags:
- linux
- tech
- unix
file: 2011-09-06-fsck-force-a-filesystem-check-on-next-reboot.md
published: True
pubdate: Tue, 06 Sep 2011 00:00:00 +0000
