author: bencane
comments: true
date: 2011-09-08 20:01:06+00:00
popularity: None
slug: mount-disabling-execution-of-scripts
title: 'mount: Disabling execution of scripts'
post_id: 48
categories:
- Administration
- Best Practices
- How To &amp; Tutorials
- Linux
- Linux Commands
- Security
tags:
- linux
- tech
- unix
file: 2011-09-08-mount-disabling-execution-of-scripts.md
published: True
pubdate: Thu, 08 Sep 2011 00:00:00 +0000
