author: bencane
comments: true
date: 2011-10-12 01:11:00+00:00
popularity: None
slug: virtualbox-mom-please-stop-getting-spyware-cheap-vdi
title: 'VirtualBox: Mom please stop getting spyware (Cheap VDI)'
post_id: 54
categories:
- How To &amp; Tutorials
- Security
tags:
- linux
- spyware
- ubuntu
- unix
- vdi
- virtualbox
- windows
file: 2011-10-12-virtualbox-mom-please-stop-getting-spyware-cheap-vdi.md
published: True
pubdate: Wed, 12 Oct 2011 00:00:00 +0000
