author: bencane
comments: true
date: 2012-08-20 12:25:41+00:00
popularity: None
slug: advanced-linux-system-statistics-and-diagnostics-with-systemtap
title: Advanced Linux System Statistics and Diagnostics with SystemTap
post_id: 77
categories:
- All Articles
- How To &amp; Tutorials
- Linux
- Troubleshooting
tags:
- apt
- apt-get
- i/o
- iostat
- kernel
- linkedin
- linux
- linux os
- linux system
- lsof
- network
- performance issues
- process
- production server
- red hat os
- rpm
- sar
- scripts
- stat
- system statistics
- systemtap
- troubleshooting
- ubuntu
- yum
file: 2012-08-20-advanced-linux-system-statistics-and-diagnostics-with-systemtap.md
published: True
pubdate: Mon, 20 Aug 2012 00:00:00 +0000
