author: bencane
comments: true
date: 2012-08-06 14:45:13+00:00
popularity: True
slug: troubleshooting-high-io-wait-in-linux
title: Troubleshooting High I/O Wait in Linux
description: A walkthrough on how to find processes that are causing high I/O Wait on Linux Systems
post_id: 75
categories:
- Linux
- Troubleshooting
- I/O Wait
tags:
- bonnie
- cpu
- disk
- disk access
- i/o
- iostat
- linkedin
- linux
- linux os
- lsof
- proc io
- proc pid io
- process
- rrqm
- sar
- sda
- slowness
- troubleshooting
- unix
- wait
- wait state
- wrqm
file: 2012-08-06-troubleshooting-high-io-wait-in-linux.md
published: True
pubdate: Mon, 06 Aug 2012 00:00:00 +0000
