author: bencane
comments: true
date: 2012-09-17 13:55:10+00:00
popularity: True
slug: iptables-linux-firewall-rules-for-a-basic-web-server
title: 'iptables: Linux firewall rules for a basic Web Server'
description: A walkthrough on setting up a basic Linux Firewall for Webservers with FTP, SSH, MySQL and DNS services
post_id: 79
categories:
- Administration
- Firewalls
- How To &amp; Tutorials
- Linux
- Networking
- Security
tags:
- all
- apt-get
- config
- debian
- dns
- firewall
- init
- iptables
- iptables example
- iptables how-to
- iptables rules
- iptables tutorial
- kernel
- kernel module
- linkedin
- linux
- linux firewall
- linux kernel
- linux os
- linux system
- linux tutorial
- linux web server
- netfilter
- network
- network address translation
- red hat os
- scripts
- traffic
file: 2012-09-17-iptables-linux-firewall-rules-for-a-basic-web-server.md
published: True
pubdate: Mon, 17 Sep 2012 00:00:00 +0000
