author: bencane
comments: true
date: 2012-05-27 21:00:33+00:00
popularity: True
slug: acl-using-access-control-lists-on-linux
title: 'ACL: Using Access Control Lists on Linux'
description: A tutorial showing how to enable Linux Access Control Lists as well as how to use ACL's to go beyond basic permissions
post_id: 70
categories:
- Administration
- How To &amp; Tutorials
- Linux
- Security
tags:
- acl
- debian
- filesystems
- kernel
- linkedin
- linux
- linux os
- permissions
- redhat
- tech
- ubuntu
- unix
file: 2012-05-27-acl-using-access-control-lists-on-linux.md
published: True
pubdate: Sun, 27 May 2012 00:00:00 +0000
