author: bencane
comments: true
date: 2012-07-08 00:22:24+00:00
popularity: True
slug: sar-sysstat-linux-performance-statistics-with-ease
title: 'Sar & Sysstat: Linux Performance Statistics with Ease'
description: Tutorial on installing the sysstat package and using sar to identify performance statistics
post_id: 72
categories:
- How To &amp; Tutorials
- Linux Performance Tuning
- System Monitoring
- Linux
- Linux Commands
tags:
- cpu
- cpuinfo
- cronjob
- i/o
- iostat
- linkedin
- linux
- linux os
- mpstat
- network
- performance monitoring
- sadf
- sar
- sar command
- sar system
- swap
- sysstat
- sysstat package
- system activity reporter
- system statistics
- systems performance
- unix
- unix tools
file: 2012-07-08-sar-sysstat-linux-performance-statistics-with-ease.md
published: True
pubdate: Sun, 08 Jul 2012 00:00:00 +0000
