author: bencane
comments: true
date: 2012-02-26 18:04:56+00:00
popularity: None
slug: sudoedit-securely-allow-users-to-edit-files
title: 'Sudoedit: Securely allow users to edit files'
post_id: 65
categories:
- Administration
- All Articles
- Best Practices
- How To &amp; Tutorials
- Linux
- Linux Commands
- Security
- Unix
- Unix Commands
tags:
- editors
- linkedin
- linux
- security
- sudo
- sudoedit
- tech
- unix
- vi
file: 2012-02-26-sudoedit-securely-allow-users-to-edit-files.md
published: True
pubdate: Sun, 26 Feb 2012 00:00:00 +0000
