author: bencane
comments: true
date: 2012-04-16 15:38:12+00:00
popularity: None
slug: unix-shell-the-art-of-io-redirection
title: 'Unix Shell: The Art of I/O Redirection'
post_id: 68
categories:
- All Articles
- Command Line
- How To &amp; Tutorials
- Linux
- Linux Commands
- Programming
- Shell Scripting
- Unix
- Unix Commands
tags:
- bash
- bash redirection
- linkedin
- linux
- oracle
- osx
- shell
- solaris
- tech
- ubuntu
- unix
file: 2012-04-16-unix-shell-the-art-of-io-redirection.md
published: True
pubdate: Mon, 16 Apr 2012 00:00:00 +0000
