author: bencane
comments: true
date: 2013-09-03 08:00:23+00:00
popularity: True
slug: getting-started-with-saltstack-by-example-automatically-installing-nginx
title: 'Getting started with SaltStack by example: Automatically Installing nginx'
description: A walkthrough on installing and setting up SaltStack using nginx as an example usecase
thumbnail: http://bencane.com/img/thumbnails/saltstack.jpg
post_id: 100
categories:
- Administration
- How To &amp; Tutorials
- Linux
tags:
- automation tool
- automation tools
- configuration management
- enterprise
- enterprise configuration management
- linux
- linux os
- nginx
- provisioning
- red hat os
- saltstack
- sysadmin
- systems administration
- systems automation
- ubuntu
- ubuntu os
file: 2013-09-03-getting-started-with-saltstack-by-example-automatically-installing-nginx.md
published: True
pubdate: Tue, 03 Sep 2013 00:00:00 +0000
