author: bencane
comments: true
date: 2013-09-16 09:00:13+00:00
popularity: None
slug: understanding-a-little-more-about-etcprofile-and-etcbashrc
title: Understanding a little more about /etc/profile and /etc/bashrc
description: What is the /etc/profile and /etc/bashrc files? What do they do? Read more to find out.
post_id: 102
categories:
- All Articles
- Best Practices
- Linux
- Red Hat
- SysAdmin Basics
- Ubuntu
tags:
- /etc/bashrc
- /etc/profile
- bash
- bashrc
- gnu linux
- linux distributions
- linux os
- linux server
- linux system
- linux tutorial
- linux version
- profile
- red hat
- red hat linux
- red hat os
- redhat
- servers
- shell
- shell best practices
- shell commands
- shell scripting
- ssh
- ubuntu
- ubuntu linux
- ubuntu os
- unix and linux
file: 2013-09-16-understanding-a-little-more-about-etcprofile-and-etcbashrc.md
published: True
pubdate: Mon, 16 Sep 2013 00:00:00 +0000
