author: bencane
comments: true
date: 2013-07-22 14:00:26+00:00
popularity: None
slug: ssh-disable-host-checking-for-scripts-automation
title: 'SSH: Disable Host Checking for Scripts & Automation'
description: How to disable SSH host checking for both scripts and lazy users
post_id: 96
categories:
- Administration
- How To &amp; Tutorials
- Programming
- Security
- Shell Scripting
tags:
- bash
- known hosts file
- known_hosts
- linux
- linux os
- red hat os
- rsa key
- shell
- shell scripting
- ssh
- ssh keys
- ssh-keygen
file: 2013-07-22-ssh-disable-host-checking-for-scripts-automation.md
published: True
pubdate: Mon, 22 Jul 2013 00:00:00 +0000
