author: bencane
comments: true
date: 2013-10-10 13:00:08+00:00
popularity: None
slug: symlinks-vs-hardlinks-and-how-to-create-them
title: Symlinks vs Hardlinks and how to create them
description: An article that explains the differences between symlinks and hardlinks and how to create them
post_id: 105
categories:
- All Articles
- How To &amp; Tutorials
- Linux
- SysAdmin Basics
tags:
- filesystems
- hard link
- links
- linux
- linux server
- linux system
- linux tutorial
- red hat linux
- redhat
- symbolic link
- symlink
file: 2013-10-10-symlinks-vs-hardlinks-and-how-to-create-them.md
published: True
pubdate: Thu, 10 Oct 2013 00:00:00 +0000
