author: bencane
comments: true
date: 2013-09-09 09:24:03+00:00
popularity: None
slug: setting-process-cpu-priority-with-nice-and-renice
title: Setting process CPU priority with nice and renice
description: How to set a CPU priority (niceness) value with the nice and renice commands
post_id: 101
categories:
- All Articles
- Command Line
- How To &amp; Tutorials
- Linux
- Linux Commands
- SysAdmin Basics
- Unix
- Unix Commands
tags:
- bash
- change process niceness
- cpu
- cpu priority
- linux
- linux niceness
- linux os
- linux scheduler
- nice
- niceness
- processes
- renice
- unix
file: 2013-09-09-setting-process-cpu-priority-with-nice-and-renice.md
published: True
pubdate: Mon, 09 Sep 2013 00:00:00 +0000
