author: bencane
comments: true
date: 2013-09-23 09:49:08+00:00
popularity: None
slug: remote-command-execution-with-saltstack
title: Remote Command Execution with SaltStack
description: A guide on using the Remote Command Execution abilities of SaltStack
thumbnail: http://bencane.com/img/thumbnails/saltstack.jpg
post_id: 103
categories:
- Administration
- All Articles
- Automation Tools
- Command Line
- How To &amp; Tutorials
- Linux
- Saltstack
tags:
- automation tool
- automation tools
- configuration management
- linux os
- nginx
- saltstack
- scripting
- scripts
- servers
- shell commands
- ssh
- systems automation
- ubuntu linux
- ubuntu os
- unix
- unix and linux
- unix linux
file: 2013-09-23-remote-command-execution-with-saltstack.md
published: True
pubdate: Mon, 23 Sep 2013 00:00:00 +0000
