author: bencane
comments: true
date: 2013-08-28 06:08:03+00:00
popularity: None
slug: finding-the-os-version-distribution-in-linux
title: Finding the OS version & Distribution in Linux
description: A simple trick on finding out the OS version and Distribution of a Linux system you have command line access to
post_id: 99
categories:
- Command Line
- How To &amp; Tutorials
- Linux Commands
- Linux Distributions
- Red Hat
- SysAdmin Basics
- Ubuntu
tags:
- config
- debian
- kernel version
- linux
- linux os
- linux version
- lsb-release
- os version
- red hat linux
- red hat os
- redhat
- redhat-release
- release
- scripts
- ubuntu
- ubuntu linux
file: 2013-08-28-finding-the-os-version-distribution-in-linux.md
published: True
pubdate: Wed, 28 Aug 2013 00:00:00 +0000
