author: bencane
comments: true
date: 2013-11-12 08:00:52+00:00
popularity: True
slug: installing-redis-and-setting-up-master-slave-replication
title: Installing Redis and setting up Master - Slave Replication
description: A guide on how to install Redis and setup Master - Slave replication between two or more Redis instances
thumbnail: http://bencane.com/img/thumbnails/redis.png
post_id: 109
categories:
- Applications
- Databases
- How To &amp; Tutorials
- Redis
tags:
- high availability
- redis
- replication
- linux
- nosql databases
- nosql
- in memory cache
- memcache
- redis replication
file: 2013-11-12-installing-redis-and-setting-up-master-slave-replication.md
published: True
pubdate: Tue, 12 Nov 2013 00:00:00 +0000
