author: bencane
comments: true
date: 2013-06-24 14:00:20+00:00
popularity: None
slug: adding-and-modifying-users-groups-in-linux
title: Adding and Modifying Users and Groups in Linux
description: An indepth guide on how to create and modify users and some simple tips that make user administration less of a nightmare
post_id: 95
categories:
- Administration
- All Articles
- Best Practices
- How To &amp; Tutorials
- SysAdmin Basics
tags:
- home directories
- linux
- linux os
- red hat os
- systems administration
- useradd
- usermod
file: 2013-06-24-adding-and-modifying-users-groups-in-linux.md
published: True
pubdate: Mon, 24 Jun 2013 00:00:00 +0000
