author: madflojo
date: 2016-07-19 10:30:00-07:00
pubdate: Tue, 19 Jul 2016 10:30:00 -07:00
popularity: False
slug: using-salt-ssh-to-install-salt
title: Using salt-ssh to install Salt
description: Using SaltStack's ability to run agentless over SSH to install the salt-minion agent
post_id: 131
read_time: 15
categories:
  - Linux
  - SaltStack
tags:
  - linux
  - SaltStack
  - salt-ssh
  - salt-minion
  - minion-less salt
  - salt
file: 2016-07-19-using-salt-ssh-to-install-salt.md
published: True
